language: node_js
node_js: "10.15"
cache: yarn

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: scripts/deploy.js SERVICE_NAME
  install: skip
  env:
    - "ENVIRONMENT=production"

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - <<: *production-job
      name: GraphQL Service
      script: scripts/deploy.js graphql

    - <<: *production-job
      name: Ember Service
      script: scripts/deploy.js app

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
